PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE Category(
Name VARCHAR UNIQUE NOT NULL PRIMARY KEY,
Description TEXT);
CREATE TABLE Product(
Name VARCHAR UNIQUE NOT NULL PRIMARY KEY,
Price INTEGER NOT NULL,
Description TEXT,
Discount INTEGER,
Discussion VARCHAR,
Picture VARCHAR,
Watt FLOAT);
CREATE TABLE Include(
Model_Name VARCHAR NOT NULL REFERENCES Model(Name) ON UPDATE RESTRICT ON DELETE CASCADE,
Product_Name VARCHAR NOT NULL REFERENCES Product(Name) ON UPDATE RESTRICT ON DELETE CASCADE);
CREATE TABLE Brand(
Name VARCHAR UNIQUE NOT NULL PRIMARY KEY,
Description TEXT);
CREATE TABLE Make(
Brand_Name VARCHAR NOT NULL REFERENCES Brand(Name) ON UPDATE RESTRICT ON DELETE CASCADE,
Product_Name VARCHAR NOT NULL REFERENCES Product(Name) ON UPDATE RESTRICT ON DELETE CASCADE);
CREATE TABLE User(
Name VARCHAR NOT NULL UNIQUE PRIMARY KEY,
Password CHARACTER NOT NULL,
Identity CHARACTOR NOT NULL);
CREATE TABLE ProductList(
ID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
Total_Price INTEGER,
Create_Time DATATIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
User_Name VARCHAR,
CONSTRAINT Save FOREIGN KEY (User_Name) REFERENCES User(Name) ON UPDATE RESTRICT ON DELETE CASCADE);
CREATE TABLE Contain(
Product_Count INTEGER,
Product_Name VARCHAR NOT NULL REFERENCES Product(Name) ON UPDATE RESTRICT ON DELETE CASCADE,
ProductList_ID INTEGER NOT NULL REFERENCES ProductList(ID) ON UPDATE RESTRICT ON DELETE CASCADE);
CREATE TABLE ProductGPU(
Product_Name VARCHAR NOT NULL PRIMARY KEY REFERENCES Product(Name) ON UPDATE RESTRICT ON DELETE CASCADE,
ClockRate CHARACTER,
ThreadNum INT);
CREATE TABLE ProductCPU(
Product_Name VARCHAR NOT NULL PRIMARY KEY REFERENCES Product(Name) ON UPDATE RESTRICT ON DELETE CASCADE,
ClockRate CHARACTER,
CoreNum INT);
CREATE TABLE ProductRAM(
Product_Name VARCHAR NOT NULL PRIMARY KEY REFERENCES Product(Name) ON UPDATE RESTRICT ON DELETE CASCADE,
ClockRate CHARACTER,
Capacity CHARACTER);
DELETE FROM sqlite_sequence;
COMMIT;
